feltcoop/felt-server

LICENSE
README.md
package.json

This adds the MIT license and some metadata like the description and author.

add license and package metadata

---

README.md
package-lock.json
package.json
src/hooks.ts
src/routes/index.svelte

This updates the name of the project to `@feltcoop/felt-server` and deletes some template-specific stuff.

rename to felt-server

---

.github/workflows/build.yml

Adds a `build` file for github actions

Set up an initial actions file

---

.vscode/settings.json

This adds a new root directory, `.vscode`, and a single setting, `formatOnSave` set to `true`. It's a much nicer experience for users to have this out of the box. Gro provides formatting with Prettier and this should be the last thing needed to get automatic formatting in all of our major file types.

add vscode settings to format on save

---

src/deploy.task.ts

For issue #6 
Adds a first pass deploy command

First pass deploy

---

src/communities/communityMiddleware.ts
src/db/Database.ts
src/db/seed.ts
src/lib/LoginForm.svelte
src/lib/LogoutForm.svelte
src/lib/SideNav.svelte
src/routes/index.svelte
src/session/loginMiddleware.ts
src/session/sessionAccountMiddleware.ts
src/vocab/user/user.ts

Story for issue #7 
This PR removes the original disk based DB & ports to the postgres system. There may be some lines that change `User` -> `Account` but the full refactor will come in a later PR. But it will now login/create/read user accounts from the DB.
It also currently has an issue where when you logout or login; the SideNav component doesn't update the underlying `community` prop & I'm not quite sure how to fix that yet.

Replace disk write

---

src/communities/communityMiddleware.ts
src/db/Database.ts
src/db/seed.ts
src/hooks.ts
src/lib/Echo.svelte
src/lib/LoginForm.svelte
src/lib/LogoutForm.svelte
src/routes/index.svelte
src/server/ApiServer.ts
src/session/clientSession.ts
src/session/loginMiddleware.ts
src/session/logoutMiddleware.ts
src/session/sessionAccountMiddleware.ts
src/vocab/account/account.ts

This PR refactors the original "user" vocab to "account".

Refactor `user` to `account`

---

src/db/Database.ts
src/db/seed.ts
src/server/ApiServer.ts
src/spaces/space.ts
src/spaces/spaceMiddleware.ts

This PR adds a Space model/interface; defines a table for it & some initial data in the seed file; and has a simple query to read from the DB for a space given an id (testable from the browser url `localhost:3000/api/v1/spaces/2`

Initial pass added Space

---

src/db/seed.ts

changes the users to `a` with password `'a'` and `b` with password `'b'`

seed update proposal

---

src/db/Database.ts
src/db/seed.ts
src/server/ApiServer.ts
src/spaces/spaceMiddleware.ts

So this adds db & seed data for relating a space to a community.
I also want to add a component that will render the url of the spaces in a nav drawer to the right of the community buttons, but I'm not really 100% sure where to start on the architecture...
would appreciate thoughts & feedback!

Added  community-space relations

---

README.md

This cleans up the readme from our initial template fork.

merge template deps into credits

---

src/db/Database.ts
src/db/seed.ts
src/lib/ChatRoom.svelte
src/lib/SpaceNav.svelte
src/lib/Workspace.svelte
src/posts/postMiddleware.ts
src/routes/index.svelte
src/server/ApiServer.ts

Here's a PR that connects posts in the DB to their respective spaces on the front end.

Render posts by space

---

src/db/Database.ts
src/lib/ChatRoom.svelte
src/posts/postMiddleware.ts
src/server/ApiServer.ts

This is an initial pass at a create posts flow. It takes text from a form, passes it as content to an endpoint with the actor & space context, builds a post, and inserts it into the DB.
This flow will not dynamically re-render new posts made by anyone in the space atm.

Add create posts flow

---

src/communities/communityMiddleware.ts
src/db/Database.ts
src/lib/CommunityNav.svelte
src/server/ApiServer.ts

This PR adds the frontend and backend components for creating new communities on a felt-server instance

Add create community flow

---

src/communities/community.ts
src/communities/communityMiddleware.ts
src/db/Database.ts
src/hooks.ts
src/lib/CommunityNav.svelte
src/lib/Workspace.svelte
src/members/member.ts
src/routes/index.svelte
src/server/ApiServer.ts
src/session/clientSession.ts

This PR adds a first pass to inviting people into communities
NB: This relies on some less specified terms/relations (`friend`, `member`) & the system itself is currently non-consentful (I.e. no chance to reject an invite into a community).

Community invite

---

src/communities/communityMiddleware.ts
src/lib/CommunityNav.svelte

This PR adds full member data to community objects returned upon community creation, fixing a bug.

Return full communities upon creation

---

README.md

This copies the format we use in Felt.

clarify project status

---

package-lock.json
package.json

Upgrades Felt and Gro for the `felt-server` usecases, needed for #42 to proceed.

update felt and gro

---

package-lock.json
package.json
src/db/Database.ts
src/db/create.task.ts
src/db/destroy.task.ts
src/db/obtainDb.ts
src/db/postgres.ts
src/db/seed.task.ts
src/deploy.task.ts
src/hooks.ts
src/lib/Echo.svelte
src/lib/SpaceNav.svelte
src/lib/Workspace.svelte
src/lib/socketStore.ts
src/routes/index.svelte
src/server/ApiServer.ts
src/server/WebsocketServer.ts
src/server/cookie-session.d.ts
src/session/loginMiddleware.ts
svelte.config.js

Currently just a draft.
I thought I had found a way to parse the cookie from outside the middleware/ApiServer context, but I've run into a weird bug. 
As is, the server fails to load at runtime citing the following error:
```
ReferenceError: require is not defined
at /node_modules/cookie-session/index.js:15:13
at instantiateModule (/home/hreed/git/felt-server/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68693:166)
```
Presumably because of the work I'm doing in the `hooks.ts` file.
But here comes the weird bit. If I think fudge the `cookie-session` import in the `package.json`, everything works!? Server loads, name gets pulled out of cookie, everything is grand. Of course then an npm i fails.
@ryanatkn do you have any insight into what might be going on & any potentially remedies or …

Fix cookie session

---

package-lock.json
package.json
src/db/Database.ts
src/deploy.task.ts
src/hooks.ts
src/lib/ChatRoom.svelte
src/lib/Echo.svelte
src/lib/socketStore.ts
src/server/WebsocketServer.ts

Upgrades Felt, fixes some minor things, and cleans up some imports.

upgrade felt

---

src/lib/ui/Chat_Room.svelte
src/lib/ui/Post_List.svelte
src/lib/ui/Workspace.svelte

Quick fix to get account names rendering for posts

Add logic for rendering names in chat

---

src/lib/db/Database.ts
src/lib/session/client_session.ts
src/lib/vocab/entity/entity.ts

This was just placeholder code which has since been replaced by real tables and data.

delete unused entity object

---

src/lib/communities/community.ts
src/lib/ui/Chat_Room.svelte
src/lib/ui/Community_Nav.svelte
src/lib/ui/Post_List.svelte
src/lib/ui/Workspace.svelte
src/routes/index.svelte

This fixes an inefficient name lookup for users in a chat room. Per a conversation with Ryan today we are going to try and keep things normalized until they reach the client, where we can (at a later date) build out a better data access architecture for the system.
For now, this just get's things looking nice & fixes an O(n) lookup

Fix data query for member names on front end

---

src/lib/ui/Community_Nav.svelte
src/lib/ui/Logout_Form.svelte
src/lib/ui/Main_Nav.svelte
src/lib/ui/Space_Nav.svelte
src/lib/ui/Workspace.svelte
src/lib/ui/Workspace_Header.svelte
src/lib/ui/api.ts
src/lib/ui/style.css
src/lib/ui/ui.ts
src/routes/__layout.svelte

This is the smallest change I could think of to make mobile more usable. There's simple a button to collapse the left panel. The left panel also now has tabs to swap between the account and explorer views.

unbreak mobile layout

---

package-lock.json
package.json

Upgrades Felt and Gro to the latest, mainly pulling in styling changes.

upgrade felt and gro

---

src/lib/ui/Actor_Icon.svelte
src/lib/ui/Community_Nav.svelte
src/lib/ui/Main_Nav.svelte
src/lib/ui/Post_List.svelte
src/lib/ui/Post_List_Item.svelte
src/lib/ui/Space_Nav.svelte
src/lib/ui/style.css

Adds `Actor_Icon.svelte` that uses the new seeded random `hue` calculated for each post's author.
Also removes the `disabled` state from selected buttons -- the `.selected` class should be the only modifier here I think. Disabled means something different.

add member hue colors

---

src/deploy.task.ts
src/lib/server/server.ts
src/lib/ui/Socket_Connection.svelte
svelte.config.js

This PR continues some of the earlier working of getting web sockets to run locally and prod. This does not actually authorize any requests still. Using cookie security will be in a follow up PR.

More websocket work

---

.github/workflows/check.yml
README.md
package-lock.json
package.json
src/deploy.task.ts
src/lib/ui/api.ts

Upgrades to node 16.6. On my machine I ran:
```bash
fnm install v16
fnm use v16
fnm default v16
npm i -g @feltcoop/gro # and any other globally installed npm packages you have
npm i # in each project after upgrading, might not be needed
```

upgrade required node version to 16.6

---

src/deploy.task.ts
src/infra/felt-server.conf
src/infra/initialize.task.ts
src/infra/setup.task.ts
src/restart_prod.task.ts

This PR adds a gro task for initializing a clean install Linux(Ubuntu) distro into the place where it can run a production instance of the felt-server.

Add initialize task and config file for nginx

---

src/lib/ui/Community_Nav.svelte
src/lib/ui/Main_Nav.svelte
src/lib/ui/Post_List_Item.svelte
src/lib/ui/Space_Nav.svelte
src/lib/ui/Workspace.svelte
src/lib/ui/Workspace_Header.svelte
src/lib/ui/color.ts
src/lib/ui/style.css
src/routes/__layout.svelte
svelte.config.js

This makes the `Main_Nav` a permanent fixture onscreen. It also flips the Svelte compiler flag `immutable` on.

make nav a permanent onscreen object

---

src/lib/server/ApiServer.ts
src/lib/server/service.ts
src/lib/server/serviceMiddleware.ts
src/lib/server/services.test.ts
src/lib/vocab/community/communityServices.ts
src/lib/vocab/file/fileServices.ts
src/lib/vocab/space/spaceServices.ts

Adds the `ServiceRequest` type, an object that wraps together the request's `params` with things like the `server` instance and authenticated `account_id`.

add service request object

---

src/lib/session/loginMiddleware.ts
src/lib/util/password.ts

This PR fixes an issue where hash generation and comparison was not being done properly for account login

Fix login bug

---

package-lock.json
package.json

Upgrades Gro and Felt to the latest versions: `npm i @feltcoop/gro@latest @feltcoop/felt@latest`
This includes the new styling changes, which always look interesting in a new context where they weren't designed!

upgrade gro and felt

---

src/lib/ui/CommunityInput.svelte

Refactors `CommunityInput.svelte` to use a `PendingButton` and display any error message. We'll want to start thinking about abstracting out reusable components/helpers/actions/etc, and this is a good example for polishing the UX of a simple form.

improve community input async behavior

---

src/lib/ui/Home.svelte
src/lib/ui/MainNav.svelte
src/lib/ui/SpaceInfo.svelte
src/lib/ui/SpaceNav.svelte
src/lib/ui/Workspace.svelte
src/lib/ui/WorkspaceHeader.svelte
src/lib/ui/ui.ts

Pair programming PR that fixes the type of the selectedSpace store

Fix readable spaces

---

src/lib/app/events.test.ts
src/lib/app/schemas.test.ts
src/lib/db/repos.test.ts
src/lib/server/ApiServer.test.ts
src/lib/server/services.test.ts
src/lib/util/password.test.ts
src/lib/vocab/persona/personaService.test.ts

Renames the `assert` helper used in tests. More context: https://github.com/feltcoop/felt/pull/140

rename assert test helper

---

package-lock.json
package.json
src/lib/ui/MainNav.svelte
src/lib/ui/Workspace.svelte

Fixes the background color of the navs on the mobile view. Also upgrades to the latest Felt and Gro. The colors looked correct on desktop, but on mobile they overlap elements and therefore need an opaque background.

fix bg color of navs on mobile

---

src/lib/ui/ui.ts

This is a minimal transformation in the client data layer toward more efficient patterns.
It changes `personasById` from a reactive map to a non-reactive map that is granularly kept in sync. The motivation is that there's significant overhead making the collections reactive and we don't use that reactivity. The `persona_id` and the store reference never change, so all that's needed is a little bookkeeping for each cache when items are added and removed. Instead of having many `persona` collections be reactive, only one will be, currently the array `personas`, but this could be anything, possibly optimized with immutable data structures.
The individual items remain reactive (e.g. if a persona name changes, everything downstream reactively updates), because the item values are stores. …

refactor persona cache

---

src/lib/app/eventTypes.ts
src/lib/server/pingService.ts
src/lib/server/service.ts
src/lib/server/services.ts
src/lib/ui/pinger.ts
src/lib/ui/ui.events.ts

Fixes the merge between #179  and #176. For some reason CI on #179 doesn't show CI failing even though it's very broken. (I should have remembered but was leaning on CI to remind me)

fix ping merge

---

src/lib/server/random.ts

Fixes tests in #182 by adding a random handler for `delete_space`.

fix tests by adding random delete_space handler

---

src/lib/ui/SpaceInput.svelte
src/lib/ui/spaceViews.ts
src/lib/vocab/space/defaultSpaces.ts
src/lib/vocab/space/space.ts

Quick PR that refactors the `SpaceType` language in spaces into `ViewType` per a previous conversation

Refactor `SpaceType` into `ViewType`

---

src/lib/app/eventTypes.ts
src/lib/server/random.ts
src/lib/server/services.ts
src/lib/ui/AccountForm.svelte
src/lib/ui/ManageMembershipForm.svelte
src/lib/ui/ui.ts
src/lib/vocab/membership/membership.events.ts
src/lib/vocab/membership/membershipRepo.ts
src/lib/vocab/membership/membershipServices.test.ts
src/lib/vocab/membership/membershipServices.ts

This PR adds the service work to the backend for leaving a community (i.e. delete membership). 
It's still a little rough on the front end though, and I'm hoping maybe we can do a little pair work on some of the UI stuff.

Leave community

---

src/lib/db/migrations/00009-refactor-entity-content-to-data.js
src/lib/ui/view/Board.svelte
src/lib/ui/view/Forum.svelte
src/lib/ui/view/Notes.svelte
src/lib/ui/view/Room.svelte

Follow on from comments hinted at in approval message of #219

Quickfix to take advantage of inherent typechecking

---

package-lock.json
package.json
src/lib/ui/LogoutForm.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/WorkspaceHeader.svelte

So like most things this took a lot less time than I was expecting lol
Timestamps were only in a couple of places on the client. I removed a couple until we have better spots for managing personas & the account. 
As for the space header & RoomItem, my CSS-fu failed me and I wasn't able to get the dates to the right without padding, which I don't think is right, since we've got flex-boxes to work with instead. But I couldn't quite figure it out. 😞

Add timestamp formatter

---

src/infra/restartProd.task.ts

Quick fix in the infra tasks to give us remote server restart. Helps with deployments :D

Fixes a bug in the restart logic

---

src/lib/db/repos.test.ts
src/lib/vocab/membership/membershipRepo.ts
src/lib/vocab/space/spaceRepo.ts

Leverages some existing `delete` repos and adds them to the repo test

Add delete spaces for tests

---

src/lib/app/dispatch.ts
src/lib/ui/WebsocketApiClient.ts
src/routes/__layout.svelte

This cleans up some hacks for handling broadcast events on the clients. It moves logic from the layout into the dispatch module with a new dispatch function that's specific to dispatching broadcast events.

refactor broadcast event dispatching

---

src/lib/server/websocketMiddleware.ts
src/lib/ui/ManageMembershipItem.svelte
src/lib/vocab/membership/membershipServices.test.ts
src/lib/vocab/membership/membershipServices.ts
src/lib/vocab/persona/personaRepo.ts

Fixes a bug where users could leave their personal community & future proofs community personas from leaving their communities.

Fix leaving personal community

---

src/lib/server/httpServiceMiddleware.ts
src/lib/server/websocketMiddleware.ts
src/lib/ui/Workspace.svelte
src/lib/ui/WorkspaceHeader.svelte
src/lib/ui/view/Home.svelte

Fixes the main layout scrollbars when the space is taller than the viewport (happens on the `Home` view on smaller screens) along with some other minor issues, like using `403` instead of `401`.

fix layout scrolling

---

src/lib/app/contextmenu/ActingPersonaContextmenu.svelte
src/lib/app/contextmenu/AppContextmenu.svelte
src/lib/app/contextmenu/CommunityContextmenu.svelte
src/lib/app/contextmenu/LinkContextmenu.svelte
src/lib/app/contextmenu/LuggageContextmenu.svelte
src/lib/app/contextmenu/SpaceContextmenu.svelte
src/lib/ui/About.svelte
src/lib/ui/Luggage.svelte
src/lib/ui/MainNav.svelte
src/lib/ui/PersonaInput.svelte
src/lib/ui/SpaceIcon.svelte
src/lib/ui/UnicodeIcon.svelte
src/lib/ui/style.css

Adds create persona functionality to the Account context menu, as well as moves a couple of other functions (logout, system about) under the entry as well.

Add create persona ux

---

src/lib/ui/MarqueeNav.svelte
src/lib/ui/WorkspaceHeader.svelte

- add community and space icons to the workspace header
- show the url in the marquee instead of repeating the space name

add icons to workspace header

---

src/lib/app/contextmenu/AppContextmenu.svelte
src/lib/ui/About.svelte
src/lib/ui/Avatar.svelte
src/lib/ui/CommunityInput.svelte
src/lib/ui/ManageMembershipForm.svelte
src/lib/ui/ManageMembershipItem.svelte
src/lib/ui/MembershipInput.svelte
src/lib/ui/MembershipInputItem.svelte
src/lib/ui/PersonaAvatar.svelte
src/lib/ui/PersonaInput.svelte
src/lib/ui/SpaceInput.svelte
src/lib/ui/contextmenu/Contextmenu.svelte
src/lib/ui/contextmenu/ContextmenuEntry.svelte
src/lib/ui/contextmenu/contextmenu.ts
src/lib/ui/style.css

Adds persona selection to the contextmenu. Semantic HTML could use improvement but the concept is implemented.

add contextmenu persona selection

---

src/lib/app/contextmenu/EntityContextmenu.svelte
src/lib/app/eventTypes.ts
src/lib/server/random.ts
src/lib/server/services.ts
src/lib/ui/BoardItem.svelte
src/lib/ui/ForumItem.svelte
src/lib/ui/NotesItem.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/ui.ts
src/lib/vocab/entity/entity.events.ts
src/lib/vocab/entity/entityData.ts
src/lib/vocab/entity/entityRepo.ts
src/lib/vocab/entity/entityServices.ts

This PR adds an event for "hard" deleting entities.
It clarifies the previous delete functionality that creates `Tombstone` entities as a "soft" delete.
It also updates some View templates to properly render `Tombstone`s

Hard delete entities

---

src/lib/server/services.test.ts

This doesn't fix the heisenbug in the tests but it fixes the error reporting for it.

fix error reporting for automated service call tests

---

src/lib/ui/view/Home.svelte

This PR changes the existing Home view to match the community-rules mockup designed by @trusttri
Functionality for modifying the `rules` & `norms` sections to follow.

Initial styling based on mockup

---

src/lib/ui/view/Voice.svelte
src/lib/ui/view/components.ts
src/lib/vocab/view/view.ts

remove voice stuff

---

src/lib/ui/EntityInput.svelte
src/lib/ui/TodoItem.svelte
src/lib/ui/TodoItems.svelte
src/lib/ui/view/Todo.svelte

This PR makes an effort to implement the polished UX for the Todo view outlined here: https://mydraft.cc/c8keok7malqvgmbsvncg 
The "clear done" I think will be a follow up for after we get our store situation figured out.

Polish todo ux

---

package-lock.json
package.json
src/lib/vocab/space/spaceHelpers.ts

Should pass CI once this PR is merged and Felt is updated: <https://github.com/feltcoop/felt/pull/189>

properly count graphemes when validating space icons

---

src/lib/vocab/community/communityServices.test.ts
src/lib/vocab/community/communityServices.ts

Adds a check for duplicate community names and adds a test.

check for duplicate community names

---

src/lib/app/eventTypes.ts
src/lib/app/events.ts
src/lib/server/random.ts
src/lib/server/services.ts
src/lib/vocab/persona/personaEvents.ts
src/lib/vocab/persona/personaServices.ts

This PR adds a service event for reading a Persona's data given its ID.

Added readPersona event

---

src/lib/server/servicesIntegration.test.ts
src/lib/vocab/entity/entityMutations.ts

rename files vars

---

package-lock.json
package.json
src/lib/ui/BoardItem.svelte
src/lib/ui/ForumItem.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/contextmenu/contextmenu.ts
src/lib/ui/style.css
src/lib/vocab/entity/EntityRepo.ts
src/lib/vocab/entity/entityServices.test.ts
src/lib/vocab/entity/entityServices.ts

parallelizes entities creation in the entityServices test, and also cleans up a couple unrelated things

parallelize entity creation in entityServices test

---

src/lib/util/randomEventParams.ts

We had some code that was unnecessary and could possibly cause an infinite loop if something changed in the future, rather than properly failing. (not a huge deal, but hard to debug especially in CI)
Also cleans up some todos in the same module.

fix a random method for event params

---

src/lib/ui/BoardItem.svelte
src/lib/ui/EntityContent.svelte
src/lib/ui/EntityEditor.svelte
src/lib/ui/EntityTree.svelte
src/lib/ui/ForumItem.svelte
src/lib/ui/NotesItem.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/SpaceView.svelte
src/lib/ui/SvastText.svelte
src/lib/ui/TodoItem.svelte
src/lib/ui/view/Home.svelte

Render entity content with a new `EntityContent` component -- chat messages now linkify :link:

add entity content component

---

src/lib/ui/contextmenu/Contextmenu.svelte
src/lib/ui/contextmenu/ContextmenuEntry.svelte
src/lib/ui/contextmenu/ContextmenuSubmenu.svelte
src/lib/ui/contextmenu/contextmenu.ts

Really tricky bug -- I explain more in a comment.

fix contextmenu on mobile

---

src/lib/ui/CommunityInput.svelte
src/lib/vocab/community/communityMutations.ts

Same problem as #374 but for `CreateCommunity`

fix create community redirect

---

README.md

[Jane Im](https://imjane.net) (@trusttri) has been helping us with design ideas and creating mockups, both related to her research on [consentful.systems](https://consentful.systems/) and unreleased work, and this adds a credit line to the readme. Also something to remember when we add an "about" page or something to the website.

add credit line for Jane Im

---

src/lib/ui/PersonaInput.svelte
src/lib/vocab/persona/personaMutations.ts

same as #374 for the `CreateAccountPersona` event redirect

fix create persona redirect

---

src/lib/app/eventTypes.ts
src/lib/db/migrations/00023-rename-actor-to-persona.js
src/lib/db/seed.ts
src/lib/ui/BoardItem.svelte
src/lib/ui/EntityCell.svelte
src/lib/ui/EntityEditor.svelte
src/lib/ui/EntityInput.svelte
src/lib/ui/EntityItem.svelte
src/lib/ui/ForumItem.svelte
src/lib/ui/NotesItem.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/TodoItem.svelte
src/lib/ui/view/Board.svelte
src/lib/ui/view/Forum.svelte
src/lib/ui/view/Home.svelte
src/lib/ui/view/Notes.svelte
src/lib/ui/view/Room.svelte
src/lib/ui/view/Todo.svelte
src/lib/util/randomVocab.ts
src/lib/vocab/entity/EntityRepo.ts
src/lib/vocab/entity/entity.schema.ts
src/lib/vocab/entity/entity.ts
src/lib/vocab/entity/entityEvents.ts
src/lib/vocab/entity/entityServices.test.ts
src/lib/vocab/entity/entityServices.ts
src/lib/vocab/persona/personaServices.ts

This PR came out of a conversation we had about the terminology of `actor` (which is used in the ActivityStreams spec) & persona (which is essentially our system implementation of actor). This brings the system into an internal alignment.

Refactors the `actor_id` attribute to `persona_id` on entities

---

package-lock.json
package.json
src/lib/ui/style.css
src/lib/vocab/entity/entityServices.test.ts

see <https://github.com/feltcoop/felt/pull/205>

upstream fade-in animation

---

README.md

Changes the line crediting Jane based on feedback.

update credit line for Jane Im

---

src/lib/ui/contextmenu/contextmenu.ts

fix contextmenu bug

---

package-lock.json
package.json
src/lib/ui/About.svelte
src/lib/ui/BoardItem.svelte
src/lib/ui/CommunityDelete.svelte
src/lib/ui/CommunityEditor.svelte
src/lib/ui/CommunityInput.svelte
src/lib/ui/EntityEditor.svelte
src/lib/ui/EntityInput.svelte
src/lib/ui/ErrorMessage.svelte
src/lib/ui/ForumItem.svelte
src/lib/ui/ManageMembershipForm.svelte
src/lib/ui/MembershipInput.svelte
src/lib/ui/NotesItem.svelte
src/lib/ui/Onboard.svelte
src/lib/ui/PersonaInput.svelte
src/lib/ui/PropertyEditor.svelte
src/lib/ui/RoomItem.svelte
src/lib/ui/SpaceDelete.svelte
src/lib/ui/SpaceEditor.svelte
src/lib/ui/SpaceInput.svelte
src/lib/ui/view/Home.svelte
src/routes/__layout.svelte
src/routes/docs/index.svelte

might be some sneaky styling changes due to `.markup`

upgrade deps

---

src/lib/ui/ui.ts
src/lib/vocab/entity/entityMutationHelpers.ts
src/lib/vocab/entity/entityMutations.ts

So in my previous PR (#393) I replaced some code doing store initialization for entities in the ui file (line 294) with a call to the updateEntity function.
That function though relies upon `dispatch` & I seem to have broken something trying to get it to work nicely. :(

fix `dispatch` runtime issue

---

src/lib/ui/TodoItem.svelte
src/lib/ui/TodoItems.svelte
src/lib/ui/ui.ts
src/lib/ui/view/Todo.svelte
src/lib/vocab/entity/entityMutationHelpers.ts
src/lib/vocab/entity/entityMutations.ts
src/lib/vocab/tie/tieMutations.ts

This PR adds stores for ties on entities, granting reactive power to views

Add tie stores

---

src/lib/app/dispatch.ts
src/lib/ui/TodoItem.svelte
src/lib/vocab/entity/entityMutationHelpers.ts
src/lib/vocab/entity/entityMutations.ts
src/lib/vocab/tie/tieMutations.ts

This PR updates the DeleteEntity flow to properly evict ties related to the entity from the UI stores.

Entity todo facilitate deletion

---

src/lib/ui/Link.svelte

Changes embedded links to open in a new tab if external.

add target for external links
