package.json
Per our tests today, things are broken somewhere between 14.0 and 14.16 due to module API stabilization, so we're planting our nvms and fnms in the ground here until October, probably.
=> update package.json engines to >= 14.16.0

.github/workflows/build.yml, package-lock.json, package.json, src/db/Database.ts, src/db/README.md, src/db/db.ts, src/db/postgres-types.d.ts, src/db/postgres.ts, src/db/seed.ts, src/server/ApiServer.test.ts, src/server/ApiServer.ts, src/server/server.ts, tsconfig.json
This adds the dependency [`postgres`](https://github.com/porsager/postgres/) to drive the database. It includes some simple examples in a temporary location and some initial documentation in a readme.
In a followup PR we could implement the methods in `src/db/Database.ts` using its `sql` property, and refactor into nice repos files or something, e.g. `src/account/repo.ts` alongside a `src/account/model.ts`. (possibly namespaced off of the root at `src/vocab/account/*` or something)
=> add postgres and simple examples

package-lock.json, src/db/seed.ts, src/hooks.ts, src/lib/SideNav.svelte, src/routes/index.svelte
So this PR covers two elements related to a communities view
1. It extends the DB seed file to add a `communities` table & a relational `accounts_communities` table, plus dummy data
2. It adds a SideNav component that I've filled with some stub buttons (to be generated programmatically later).
Once this gets merged I'm going to add a route to get all the communities for a given account, then see if I can't populate the sidebar with that info programmatically.
Here's a REPL example of the sidenav:
https://svelte.dev/repl/588ac19e1ea54d99a41ac2e3734d3c75?version=3.37.0
=> Add communities view

src/communities/community.ts, src/db/Database.ts, src/lib/CommunityNav.svelte, src/lib/SideNav.svelte, src/lib/SpaceNav.svelte, src/lib/Workspace.svelte, src/routes/index.svelte
This PR adds `spaces` as an attribute of a community, pushes it up with an account's context, and then renders it.
@ryanatkn I think I'm barking up the wrong tree as far as reactivity goes. I was trying to get the selected community back up into the workspace and down into the `SpacesNav` but it clearly isn't working.
All the front end architecture is WIP, so open to any suggestions or paths forward there.
=> Add spaces to context

src/app.css, src/routes/$layout.svelte
This adds `src/app.css` and imports it from `src/routes/$layout.svelte`, which is the pattern the SvelteKit default now uses to get a global CSS file loaded on every page. We want to keep it small, but this is the place to put our global (static) styles. We'll eventually move this code into `@feltcoop/felt`, but it helps flesh out our requirements.
Now when we add component styles, like to buttons, we can decide whether they're global design system rules, or specific to the component.
=> add global app.css

src/lib/ChatRoom.svelte, src/lib/CommunityNav.svelte, src/lib/SpaceNav.svelte, src/lib/Workspace.svelte
This PR fixes an issue where new accounts were bugging out due to missing communities & spaces. This adds some more front end validation to help render the screen for when accounts have no community, or when a community has no spaces.
I also tweaked the styling to make the community nav stand out, & put the chat input box at the bottom of it's component.
=> Added some front end logic to fix state errors with new accounts

src/db/README.md
This documents the steps needed to get a fresh Postgres installation ready with `felt-server`'s default values. It's copy-paste from our private notes.
=> add instructions to setup postgres defaults

package-lock.json, package.json, src/app.css, src/routes/__layout.svelte, src/routes/index.svelte
closes #56 
Imports the newly published `@feltcoop/felt/ui/style.css` in the global layout. To render document-formatted text and other markup, wrap it in `@feltcoop/felt/ui/Markup.svelte` to apply correct styles.
=> import styles from felt

package-lock.json, package.json, src/lib/ui/Socket_Connection.svelte, src/routes/__layout.svelte, svelte.config.js
Adds the `devmode` top-level component and context store. To use it from anywhere in the component tree during component initialization:
```ts
import {get_devmode} from '@feltcoop/felt/ui/devmode.js';
const devmode = get_devmode(); // reads from context
$devmode; // writable store
```
Also had to add the `optimizeDeps` Vite config option to fix bundling, but unlike the SSR error we don't need the `ssr` config. Without the `optimizeDeps` override, it fails to prebundle properly, messing up Svelte's initialization. The newly imported Felt code uses Svelte's context helpers, so that's the root cause of this specific issue.
=> add devmode

src/lib/ui/Main_Nav.svelte, src/lib/ui/Socket_Connection.svelte, src/lib/ui/socket.ts
Fixes the socket disconnect issue, so when the user logs out it'll disconnect. It's being encapsulated in the `Socket_Connection.svelte` component, so mounting/unmounting that component controls the socket lifecycle. I don't love the flexibility this gives us with putting the socket in context and having it tied to the component lifecycle, but it's fine for now. There's a source of truth issue here with the socket url that I don't know how to fix. We know we need multiple concurrent sockets to various servers, so I suspect we'll want to rework this to be more data-driven from the top.
Also refactors the `Socket_Store` to match the pattern elsewhere, giving us better types.
=> fix socket disconnect

src/lib/ui/Main_Nav.svelte, src/lib/ui/Socket_Connection.svelte, src/routes/__layout.svelte
Currently the socket is disconnected when the `Socket_Connection` component is unmounted. This change decouples the socket connection from its controls, hoisting the connection logic to the top-level layout, making the `Socket_Connection` UI optional. Without this change, the socket disconnects when the luggage goes into the closet!
=> refactor socket to not be dependent on ui component

package-lock.json, package.json, src/lib/db/Database.ts, src/lib/db/seed.ts, src/lib/spaces/space_middleware.ts, src/lib/ui/Chat.svelte, src/lib/ui/Community_Nav.svelte, src/lib/ui/Iframe.svelte, src/lib/ui/Note_List.svelte, src/lib/ui/Note_List_Item.svelte, src/lib/ui/Notes.svelte, src/lib/ui/Pending_Animation_Overlay.svelte, src/lib/ui/Post_List.svelte, src/lib/ui/Space_Input.svelte, src/lib/ui/Space_View.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/api.ts, src/lib/ui/style.css, src/routes/__layout.svelte
- renders spaces based on their `media_type`
- renames `Chat` from `Chat_Room`
- adds a `Notes` component and seeds one
- adds an `Iframe` component and seeds one
- upgrades Felt
I originally tried to iframe Felt's library, but it loads, renders, and then errors with `The operation is insecure.`. Quick search didn't yield a workaround; not sure how to proceed right now, so I changed it to load dealt.dev/tar. Might be a sandbox attribute or something in SvelteKit? Based on the error, my guess is it's related to how SvelteKit is doing routing but I'm alright with iframing something else for now.
=> add space type rendering for notes and iframes

src/lib/ui/Chat.svelte, src/lib/ui/Community_Input.svelte, src/lib/ui/Community_Nav.svelte, src/lib/ui/Main_Nav.svelte, src/lib/ui/Member_Input.svelte, src/lib/ui/Notes.svelte, src/lib/ui/Socket_Connection.svelte, src/lib/ui/Space_Input.svelte, src/lib/ui/Space_Nav.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/Workspace_Header.svelte, src/lib/ui/app.ts, src/lib/ui/data.ts, src/lib/ui/style.css, src/lib/ui/ui.ts, src/routes/__layout.svelte
Makes the mobile view much better, using animations and responsive layout on the main menu.
Also adds an `app` context helper to keep things succinct. I think it's a good call but I could be off.
Possible followup TODOs for later PRs:
=> improve mobile view

src/lib/ui/Chat.svelte, src/lib/ui/Login_Form.svelte, src/lib/ui/Luggage.svelte, src/lib/ui/Main_Nav.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/Workspace_Header.svelte, src/lib/ui/style.css, src/routes/__layout.svelte, src/routes/index.svelte
This makes `<Luggage />` a static element onscreen: instead of rendering it in multiple places depending on app state context, it now just sits in the top left, so it just toggles stuff and is always overlays other stuff in the normal case. The `z-index` could probably be toned down from `9`, I dunno. The code now uses `.luggage-placeholder` elements in places where we need to adjust layout to accommodate the fact that the luggage is sitting atop things outside the normal layout.
Eventually it should be possible to hide and move it, probably later when we go into controls and custom options.
=> add luggage object permanence

src/hooks.ts, src/lib/db/Database.ts, src/lib/db/seed.ts, src/lib/server/Api_Server.ts, src/lib/session/client_session.ts, src/lib/session/login_middleware.ts, src/lib/session/session_account_middleware.ts, src/lib/ui/Login_Form.svelte, src/lib/ui/Logout_Form.svelte, src/lib/ui/data.ts, src/lib/vocab/account/account.ts, src/routes/index.svelte
Changes the session to use `account_id`, and then sends only a subset of fields back to the client. Not sure about the naming of the various `Account` interfaces -- I left a todo with some ideas, and it fits the current pattern. Also removes the old hacky `/context` API route.
=> security pass

package-lock.json, package.json, src/infra/deploy.task.ts, src/lib/db/create.task.ts, src/lib/db/obtain_db.ts, src/lib/db/postgres.ts, src/lib/ui/Modal.svelte, src/lib/ui/color.ts, src/routes/__layout.svelte
This makes the server always respond to iframes posting the messages `'felt__connect'` and `'felt__query'`. It's a proof of concept and it's insecure for any private data -- for now the only data it forwards is the account's `hue`.
usage in this PR: https://github.com/feltcoop/dealt/pull/29
=> add support for iframe connection and querying

src/lib/ui/api.ts, src/lib/ui/ui.ts
These aren't needed because of how they're declared, and they're error prone if included because TypeScript's rules allow them to be subtypes. (e.g. unions with types that aren't in the original signature)
=> remove unnecessary type signatures

src/lib/ui/SpaceInput.svelte, src/lib/ui/SpaceView.svelte, src/lib/vocab/space/default_spaces.ts, src/lib/vocab/space/space.ts
This PR adds a simple selector element to the new Space dialog box which allows a user to select the Type of new space.
It also adds an enumeration object (SpaceType) although I'm not sure if it's actually in the right "semantics" for our framework.
There's also currently a weird bug, where if you click into a new space just after creating it, Svelte throws a bunch of errors (see below)
=> Add space type picker

src/lib/ui/SpaceInput.svelte, src/lib/ui/SpaceView.svelte, src/lib/ui/spaceViews.ts, src/lib/vocab/space/defaultSpaces.ts, src/lib/vocab/space/space.ts
Makes space views mount generically based on their type, looking up the component from a typesafe mapping of type to component. Changes `SpaceType` to an enum and caches `spaceTypes` with type `SpaceType[]`.  This pattern could probably be improved a bit, but I think codegen ultimately will get the best results. Also improves some UX things in the space input and adds initial types for the space data that's encoded as stringified json.
Also fixes a UX issue caused by making the input a `form` in the PR that added space types -- pressing `Enter` caused the page to refresh because it caused the default `submit` action. We'll want to start looking at form components soon now that we have more use cases.
=> mount space views generically and refactor space input

src/lib/server/ApiServer.test.ts, src/lib/server/ApiServer.ts, src/lib/server/server.ts, src/lib/server/service.ts, src/lib/vocab/community/communityServices.ts, src/lib/vocab/file/fileServices.ts, src/lib/vocab/space/spaceServices.ts
This continues the work to make services declarative and data-driven. It adds an `http` object to services with `method` and `path`, e.g. `'post'` and `'/api/v1/communities/:community_id'`. The `http` name could maybe be improved, like `route`? The equivalent to `method`+`path` for websockets is simply the service `name` which corresponds to events/rpc/etc.
Since services are now mostly declared as data, it should be fairly trivial to generate some basic docs. Maybe a good first usecase for adding them to the frontend.
=> change services to have declarative http path and method

src/lib/ui/CommunityNav.svelte, src/lib/ui/MainNav.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/data.ts, src/lib/ui/ui.ts, src/routes/__layout.svelte
This is our first significant usage of [the Svelte `derived` store](https://svelte.dev/docs#derived). It sets a good pattern for hoisting often-used cached data out of the components. The `ui` store now has several store properties that can be granularly subscribed and shared app-wide.
=> refactor client state

src/hooks.ts, src/lib/session/loginMiddleware.ts, src/lib/session/sessionRepo.ts, src/lib/vocab/community/communityRepo.ts
When the browser has cookies for a deleted account (like after seeding, we don't support a delete service yet), the server was throwing an error when it tried to `loadClientSession`. The code was taking a shortcut, and now it's time to handle those errors explicitly.
=> fix session for deleted accounts

src/lib/session/loginMiddleware.ts, src/lib/util/password.ts, src/lib/vocab/account/accountRepo.ts
Fixes `account.create` to hash the password into the key with salt. Previously, any calls to `account.create` outside of the login middleware, like tests and seed, were storing the wrong value. Now the responsibility for hashing is in the correct place, inside `account.create`.
Also uses `passwordText` instead of `password` throughout `$lib/util/password.ts` to match the changes in #120
=> fix account password creation

src/lib/ui/ApiClient.ts, src/lib/ui/HttpApiClient.ts
The http client was returning malformed errors. This improves things, but it may be imperfect in some cases. There's some strangeness with trying to handle multiple classes of errors. Specifically our concept of an `ApiRequest` error has to handle not just http errors and their familiar status, but also problems like the Internet being down or the server returning a malformed result.
One weird bit is that there can be a non-status associated with failed requests, like if the device's network connection is down or if the server unexpectedly returns a non-JSON response. I added `| null` to the `status` type so it's now `number | null`, and I think this is the best way to model things, but I could be wrong. I considered a sentinel value like -1, which would mean downstream code could just …
=> fix http error handling

src/lib/ui/CommunityNav.svelte, src/lib/ui/CommunityNavButton.svelte, src/lib/ui/HttpApiClient.ts, src/lib/ui/SpaceInput.svelte, src/lib/ui/SpaceNav.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/api.ts, src/lib/ui/data.ts, src/lib/ui/ui.ts, src/lib/vocab/community/community.ts
The `CommunityModel` was an experimental pattern where we added client-side-only properties to communities returned from the server. Instead of this mode of storing and accessing data, we're moving towards having normalized immutable data. This keeps things simpler, so we don't have to modify data received from the server. We can use `WeakMap` to get the same behavior if needed.
=> remove `CommunityModel` and rearrange its data

src/lib/server/api.ts, src/lib/server/service.ts, src/lib/server/serviceMiddleware.ts, src/lib/server/services.test.ts, src/lib/server/websocketHandler.ts, src/lib/ui/ApiClient.ts, src/lib/ui/api.ts, src/lib/vocab/community/communityServices.ts, src/lib/vocab/file/fileServices.ts, src/lib/vocab/persona/personaServices.ts, src/lib/vocab/space/spaceServices.ts
Extracts the `ApiResult` type to `$lib/server/api.ts` and uses it on both the client and server:
- http service middleware uses http/`globalThis.fetch` conventions for the `status` and `ok`
- websocket middleware sends the unmodified `Result` object (for now, we may need to add more features in the future)
The `ApiResult` is now the return value of each `Service`'s `perform` function. It's then passed through to clients, rather than being a bespoke form of data+error.
=> pass through api result from services to clients

src/lib/ui/api.ts
Makes the client api randomly choose between http and websockets on every request. Might surface bugs! (made me realize http service middleware needs to broadcast just like websockets). We'll remove this after adding tests.
=> make the api randomly choose a client on every request

src/routes/__layout.svelte
Fixes some bugs/unimplemented behavior around the websocket connection. It should now sync with the session, so when you log out you drop the connection, and when you log in it gets re-established.
I added some doc comments explaining why there are two calls to `socket.disconnect();`.
=> fix socket connecting and disconnecting on state changes

src/lib/ui/ui.ts
Fixes the `create_community` API call on the client. The code wasn't handling the spaces in the return value -- it now (should) populate the local caches. It's a good example of how our sources of truth on the client are a little wonky -- maybe worth thinking through using `derived` for `selectedSpaceIdByCommunity` before merging this. Or maybe not because `selectedSpaceIdByCommunity` needs to be rethought -- it should store the selected space by the combination of community+persona like we talked about.
=> fix creating community

src/lib/ui/CommunityInput.svelte, src/lib/ui/LoginForm.svelte, src/lib/ui/Notes.svelte, src/lib/ui/PersonaInput.svelte, src/lib/ui/Room.svelte, src/lib/ui/SocketConnection.svelte, src/lib/ui/SpaceInput.svelte
This removes `type="text"` from inputs. It's the default value so there's no need to include it; only seems to serve to make us uneasily wonder, "is this needed?"
=> remove default text value from inputs

src/lib/ui/MainNav.svelte
This makes the main nav header now sticky when scrolling, instead of scrolling off the top of the page:
previously:
=> make main nav header sticky

package-lock.json, package.json, src/lib/ui/BoardItem.svelte, src/lib/ui/CommunityInput.svelte, src/lib/ui/Home.svelte, src/lib/ui/MainNav.svelte, src/lib/ui/MembershipInput.svelte, src/lib/ui/Onboard.svelte, src/lib/ui/PersonaInput.svelte, src/lib/ui/SpaceInput.svelte, src/lib/vocab/persona/personaService.test.ts, src/routes/__layout.svelte, src/routes/docs/index.svelte
Upgrades the primary dependencies, mainly SvelteKit and [@sveltejs/adapter-node](https://github.com/sveltejs/kit/tree/master/packages/adapter-node). In a followup I'll use the adapter's new middleware in production builds instead of running two separate servers.
Also removes some unused code in a test, and filters out the `Home` space type from the space input. I left a comment about implementing something more robust and configurable in the future -- for now it seems fine to just one-off hardcode this, but we'll eventually accumulate more of these details that should probably be configurable and handled generically. Following the current events pattern this could be a `SpaceInfo` object, which could have both their props schemas and this hypothetical property to disallow users creating …
=> upgrade deps

src/infra/felt-server.conf, src/infra/felt-server.gen.conf.ts, src/lib/server/random.ts, src/lib/server/serverServices.ts, src/lib/server/service.ts, src/lib/server/services.ts, src/lib/server/websocketHandler.ts, src/lib/ui/HttpApiClient.ts, src/lib/ui/WebsocketApiClient.ts, src/lib/ui/events.ts, src/lib/ui/pinger.ts, src/lib/ui/ui.events.ts, src/lib/ui/ui.ts, src/lib/vocab/persona/personaService.test.ts, src/routes/__layout.svelte
Every so often, the websocket disconnects. It seems likely caused by nginx having a 60 second timeout after no activity.
This change increases its timeout to 6 minutes per this answer: https://stackoverflow.com/a/57706152
And the client will send a `ping` event every 5 minutes to keep the connection alive. The linked answer demonstrates 24 hours but that means the server would hold onto dropped connections far too long.
Future:
- move logic to websocket store
=> increase nginx proxy timeout

src/lib/vocab/persona/personaService.test.ts, src/lib/vocab/space/spaceRepo.ts, src/lib/vocab/space/spaceServices.test.ts
This adds a test for #182. We already have an automatic smoke test created for the service, but this adds a test with two additional checks:
- ensure the space is deleted in the db (along with the `community_spaces`)
- ensure deleting the space works when it's been added to multiple communities
We don't have an API for adding a space to a second community, but if we're going to commit to supporting that functionality we'll save ourselves a lot of headache making sure the code is compatible and APIs have the correct dependencies as we write it. The test uses a direct SQL statement to add multiple communities for now with a TODO.
I also included the 1-line fix it to handle multiple communities so CI passes on this PR.
=> add delete space tests

src/lib/ui/WebsocketApiClient.ts, src/lib/util/jsonRpc.ts
Makes the JSON RPC `id` type correctly `string | number` and changes our code to use numbers, since there's mainly downsides to strings.
=> fix json rpc type and use number ids instead of string

package-lock.json, package.json, src/infra/restartProd.task.ts, src/infra/serverDeploy.task.ts, src/infra/setup.task.ts
Fixes the env usage (fixing [these hacks](https://github.com/feltcoop/felt-server/pull/177/files/b9eebf69628870a8673209159ce6cc854a1b1015..38808b937001bbc10d5a671f74c71ef6ceff5a6b)) for production tasks by upgrading Gro. (be sure to `npm i`) Removes the hacks we had in place and should hopefully work as expected! I *think* things should work but I could very well be wrong, and I may have forgotten to make some related changes.
Also uses `spawn('npx', ['gro', 'build'])` instead of `invokeTask('build')` to more robustly ensure the environment is correctly set up. The code was somewhat hackily relying on `fromEnv` not being called before build, which is not an assumption we want to make. (this is my mistake, was my suggestion, and a lesson I learned refactoring `gro publish` and `gro deploy` …
=> fix production task env

src/lib/app/dispatch.ts, src/lib/app/eventTypes.gen.ts, src/lib/app/eventTypes.ts, src/lib/app/events.test.ts, src/lib/ui/Board.svelte, src/lib/ui/CommunityInput.svelte, src/lib/ui/CommunityNavButton.svelte, src/lib/ui/Forum.svelte, src/lib/ui/LoginForm.svelte, src/lib/ui/LogoutForm.svelte, src/lib/ui/Luggage.svelte, src/lib/ui/MainNav.svelte, src/lib/ui/MarqueeButton.svelte, src/lib/ui/MembershipInputItem.svelte, src/lib/ui/Notes.svelte, src/lib/ui/PersonaInput.svelte, src/lib/ui/Room.svelte, src/lib/ui/SpaceDelete.svelte, src/lib/ui/SpaceInput.svelte, src/lib/ui/SpaceNavItem.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/app.ts, src/lib/ui/ui.ts, src/lib/util/testAppHelpers.ts, src/routes/__layout.svelte
We had this `api` object wrapper around `dispatch`, but now it's flattened out into the `app`, no more useless `api` wrapper. Mostly simplifies the code.
=> replace `api` with `dispatch`

src/lib/app/ContextmenuSlot.svelte, src/lib/app/components.ts, src/lib/app/eventTypes.ts, src/lib/server/random.ts, src/lib/ui/AccountForm.svelte, src/lib/ui/ManageMembershipForm.svelte, src/lib/ui/dialog/Dialogs.svelte, src/lib/ui/dialog/dialog.ts, src/lib/ui/ui.events.ts, src/lib/ui/ui.ts, src/routes/__layout.svelte
Adds the simplest dialog system I could think of. The motivation is to be able to open dialogs without requiring the triggering component to remain mounted. Currently we have a contextmenu button that tries to open a dialog, but it fails because when the contextmenu closes, so does its child dialog component. 
As a side effect, we'll now be able to drive dialogs throughout the whole system programmatically like any other event. (e.g. so we could use it to build a tutorial system and user macros/automations)
Uses two new events, `'OpenDialog'` and `'CloseDialog'`. I implemented it for only one existing dialog, the `ManageMembershipsForm`, because it's currently broken. 
Might want to rename the `DialogState` interface. I kept it intentionally simple so there's no wrapper store or class, …
=> add dialog system

src/lib/app/contextmenu/LinkContextmenu.svelte, src/lib/ui/Avatar.svelte, src/lib/ui/BoardItem.svelte, src/lib/ui/ForumItem.svelte, src/lib/ui/NotesItem.svelte, src/lib/ui/RoomItem.svelte, src/lib/ui/contextmenu/contextmenu.ts, src/lib/ui/style.css
Fixes text overflowing post content areas like with long links and other long unbroken strings of text.
Adds one extra property because of Firefox Android support for `white-space: break-spaces` -- https://caniuse.com/mdn-css_properties_white-space_break-spaces
Also changes the layout of the chat room messages to put the user icon to the left of the user name and text, a better use of vertical space and aligns things more nicely.
Also fixes the contextmenu shift key as we discussed.
The `Avatar` component is starting to look a bit stretched and awkward. We may want to split out `AvatarName` and `AvatarIcon` or something.
=> fix text overflow in messages

src/lib/db/migrations/00011-id-references.js
Fixes two oversights in db constraints.  The file is numbered `11` because we have two pending PRs for 9 and 10 and none of them look like they'll conflict.
=> fix two db constraints

src/lib/ui/ManageMembershipForm.svelte, src/lib/ui/ui.ts, src/routes/__layout.svelte
Before this change, sending a `ViewSpace` event didn't do any browser navigation, so it was easy to right click on an inactive space, choose the different view, and seemingly nothing would happen. Now it'll update the browser URL.
I extracted a `getCommunity` helper that's used in a few places, and will soon be replaced with a `communityById` map.
=> navigate to space on view event

src/lib/ui/CommunityInput.svelte, src/lib/ui/SpaceInput.svelte
This refactors the community and space inputs to be similar -- most of their code is now identical, and so it'll help us move towards generic handling.
- disallow creating communities with an empty string name
- disallow whitespace in the names of communities and spaces, and characters other than letters/numbers/dashes (this is temporarily overly-constrained until we decide on better rules)
- display error messages consistently
- don't close the community input if creation fails
future:
- decide on naming restrictions and implement
=> improve community and space inputs

package-lock.json, package.json, src/lib/ui/MainNav.svelte, src/lib/ui/WorkspaceHeader.svelte
Adds `svelte-check` as a dev dependency. It was removed recently in Gro, letting projects install it if they wanted it. We upgraded Gro in #217 so we haven't been getting Svelte typechecking since then in CI; we still saw it work locally if we had an old `svelte-check` installed in `node_modules`.
This newer version causes some errors due to this issue: https://github.com/sveltejs/language-tools/ issues/1341
I'll add workarounds for them. There may be a solution for the issue but I'm not sure. I proposed a possible fix but we'll see if it works.
=> add svelte-check dev dependency

src/lib/server/random.ts, src/lib/ui/ManageMembershipItem.svelte, src/lib/ui/Marquee.svelte, src/lib/ui/MembershipInput.svelte, src/lib/ui/ui.ts, src/lib/ui/view/Home.svelte, src/lib/vocab/persona/persona.ts, src/lib/vocab/persona/personaRepo.ts
=> refactor memberships fixes

package-lock.json, package.json, src/lib/ui/BoardItem.svelte, src/lib/ui/CommunityNavButton.svelte, src/lib/ui/EntityItem.svelte, src/lib/ui/ForumItem.svelte, src/lib/ui/MemberItem.svelte, src/lib/ui/NotesItem.svelte, src/lib/ui/RoomItem.svelte, src/lib/ui/ui.ts, src/routes/__layout.svelte
This changes the `ui` initialization to start up with empty values, and then calls `ui.setSession` so there's a single code path.
I also renamed a few things for clarity.
followup
- fix bug where the wrong community is initialized because it's not reading from the URL (not caused by this PR)
=> refactor initial session and session updating to a single code path

package-lock.json, package.json, src/lib/ui/contextmenu/Contextmenu.svelte, src/lib/ui/contextmenu/ContextmenuSubmenu.svelte, src/lib/ui/contextmenu/contextmenu.ts, src/lib/ui/ui.ts, src/routes/__layout.svelte
Improves the contextmenu to stay onscreen. It should choose the best placement of the pane, be reactive to window size changes, and it should work on small screens as long as there's enough width for each contextmenu pane.  (though it gets close to unusable on small screens, we'll want entirely different behavior for mobile)
We can't directly use `window.innerWidth` and `innerHeight` because they don't account for scrollbars, so to prevent scrollbars from overlapping the contextmenu, we pass it a `layout` store containing the `width` and `height` of whatever the app wants. In our case, this is the measured dimensions of `div.layout` in the root `__layout.svelte`. It seems useful to put this new `layout` store on our main `ui` object rather than hardcoding it to just the contextmenu; I …
=> keep contextmenu onscreen

src/lib/vocab/entity/entityRepo.test.ts, src/lib/vocab/entity/entityRepo.ts
Quick PR that sorts entities by their `created` timestamp in ascending order (i.e 0th index is chronologically first).
=> Add default sort by created for entities

src/lib/app/contextmenu/EntityContextmenu.svelte, src/lib/app/eventTypes.ts, src/lib/server/random.ts, src/lib/server/services.ts, src/lib/ui/ui.ts, src/lib/vocab/entity/entity.events.ts, src/lib/vocab/entity/entityRepo.ts, src/lib/vocab/entity/entityServices.ts, src/lib/vocab/space/spaceServices.ts
This PR adds both server & client functionality for deleting an Entity
A few notes:
1.) I implemented both a hard and soft delete query. Currently the logic calls the soft version. No views have been updated to reflect these "Tombstone" objects though.
2.) The client UI call to delete doesn't do anything with Entity stores, since we're planning on refactoring those soon (and I'd then have to add the space_id to the params and it would just become a Thing)
3.) There's currently no friction the delete entity action. Might want that for context deletes by default and then have views manage any "frictionless" deletes directly.
=> Add delete entity

src/lib/app/contextmenu/CommunityContextmenu.svelte
Block users from inviting users to personal communities in the UX
=> Only render the community invite entry if it's not a personal community

src/lib/app/events.test.ts
Running tests logs (but doesn't throw) an error for the `QueryEntities` event because we don't support `fetch` from the client during tests yet. Ideally it should be a thrown error, but the problem is that the event blurs the lines between client events and service events. It synchronously returns a store and then populates it, and doesn't throw an error. We can figure out a more robust fix later down the line when we figure out entity querying and using `fetch` in tests.
=> fix logged error in tests

src/lib/ui/Marquee.svelte, src/lib/ui/MarqueeNav.svelte, src/lib/ui/MemberItem.svelte, src/lib/ui/ui.ts
The `MarqueeNav` previously displayed useful information, but after adding the community icon+name to the main space header, it's now redundant. This changes its content to a single word, `Members`, along with the member count. I'm also open to just deleting it for now, but I assume we'll want a component with its name in the future once the marquee gets filled out.
I also changed `personasByCommunityId` to include only `account` personas, because the count was off otherwise. This also let us remove the hack from `MemberItem` where we excluded `community` personas. We shouldn't have to deal with those until we're ready for them.
=> simplify MarqueeNav

src/lib/ui/WorkspaceHeader.svelte
Fixes a few things in the workspace header particularly for mobile -- text no longer wraps, the luggage no longer overlaps content on small screens, and scrollbars won't appear on small screens either.
=> fix workspace header styles

src/lib/server/servicesIntegration.test.ts, src/lib/vocab/account/validateAccount.ts, src/lib/vocab/community/validateCommunity.ts, src/lib/vocab/entity/validateEntity.ts, src/lib/vocab/space/validateSpace.ts
Finishes the work we started in `$lib/server/servicesIntegration.test.ts` to convert from repo calls to performing service events. Also deletes the validation modules for vocab, because they're not used anywhere else; we'll standardize a pattern when we get to that.
There are 3 exceptions at the end that do not have service equivalents for repo methods:
- `db.repos.persona.filterByAccount`
- `db.repos.account.findById`
- `db.repos.account.findByName`
Not sure what we want to do there yet, but that'll be for a later PR.
=> convert services integration tests from repos to services

src/lib/app/contextmenu/CommunityContextmenu.svelte, src/lib/ui/CommunityAvatar.svelte, src/lib/ui/CommunityEditor.svelte, src/lib/ui/CommunitySettingsHue.svelte, src/lib/ui/EntityEditor.svelte, src/lib/ui/SpaceEditor.svelte, src/lib/ui/view/Home.svelte
- add "Edit Community" contextmenu entry which opens a new `CommunityEditor.svelte`
- move the hue settings widget from `Home.svelte` to `CommunityEditor.svelte`
- consistently use `h1` in dialog menus for the titles (we're manually centering these each time they're used, might be a good time to standardize a pattern with a class)
=> add community editor

src/lib/ui/ui.ts, src/routes/__layout.svelte
Instead of dispatching select events after creating a community or persona, this updates the URL as the source of truth, and then fixes the state to be properly reactive.
Also appears to fix the bug where newly created communities don't appear correctly selected in the nav.
=> fix redirect aftering creating a community and persona

src/lib/app/dispatch.ts, src/lib/ui/ui.ts, src/lib/util/testAppHelpers.ts, src/routes/__layout.svelte
Simplifies the role of `ui.ts` to just store and expose data now that mutations are a separate concept. It now has no knowledge of mutations at all. This makes `dispatch` responsible for looking up and applying mutations rather than pushing that concern downstream to `ui.ts`, so now `dispatch` is more clearly the point of orchestration.
=> hoist dispatching mutations from ui

package-lock.json, package.json, src/lib/db/create/create.task.ts, src/lib/db/destroy.task.ts, src/lib/db/seed.task.ts, src/lib/server/servicesIntegration.test.ts, src/lib/ui/MainNav.svelte, src/lib/ui/MarqueeButton.svelte, src/lib/ui/PropertyEditor.svelte, src/lib/ui/Workspace.svelte, src/lib/ui/contextmenu/Contextmenu.svelte, src/lib/vocab/community/CommunityRepo.ts, src/lib/vocab/entity/EntityRepo.ts, src/lib/vocab/membership/MembershipRepo.ts, src/lib/vocab/space/SpaceRepo.ts, src/lib/vocab/tie/TieRepo.ts
Previously all of the repo methods had an incorrect type. They were returning an empty array (length=0) decorated by the Postgres driver with a `count`, which for these cases is always 1, and the count wasn't accessible on the type either.
For these cases there's no useful information to return, so I removed all of the returned data properties.
This exposed the fact that `unwrap` was too opinionated, so I changed it upstream in Felt to have an optional `value`. Will remove the typecast before merging after this PR is in: https://github.com/feltcoop/felt/pull/188
=> fix repo delete method return values

src/lib/ui/MainNav.svelte, src/lib/ui/WorkspaceHeader.svelte, src/lib/ui/ui.ts
- makes the space nav have a stable sort order -- the home space is first, followed by the spaces sorted by `name`
- removes the created timestamp from the workspace header -- the same value is visible on "Edit Community", and we talked about adding a contextmenu entry to view info like this for communities/spaces, "More Info" or something
future:
- let users specify the sort order for spaces
=> sort spaces in space nav

src/lib/server/random.ts, src/lib/vocab/community/CommunityRepo.test.ts, src/lib/vocab/community/communityServices.test.ts, src/lib/vocab/entity/EntityRepo.test.ts, src/lib/vocab/membership/membershipServices.test.ts, src/lib/vocab/random.ts, src/lib/vocab/space/spaceServices.test.ts, src/lib/vocab/tie/TieRepo.test.ts
Removes the caching in the random vocab context class. Updates the random helpers to return the objects that they create, and which makes them more verbose, but then uses those objects in the tests where possible, making the tests happily less verbose.
=> remove test cache

src/lib/db/seed.ts, src/lib/server/servicesIntegration.test.ts, src/lib/vocab/membership/membershipServices.test.ts, src/lib/vocab/random.ts
Tiny change that uses the mock version of the session API in tests and db seed. The `new SessionApi(null)` is intended for websocket usage, and we may want to make that explicit with its own class and rely on typesafety instead of its current runtime `null` checks.
=> use SessionApiMock for tests and seed

src/lib/server/httpServiceMiddleware.ts, src/lib/server/websocketMiddleware.ts
- during development and tests, response data that fails validation will now throw an error, not just log (we currently perform no validation in production for outgoing data, though that may be a failsafe we want to enable, it's avoided for performance reasons)
- the http service middleware no longer has a giant try/catch block, instead it scopes it to the `service.perform` call -- any other things that can possibly error should have their own blocks (it now matches the websocket middleware)
=> improve service error handling

package-lock.json, package.json, src/lib/ui/CommunityInput.svelte, src/lib/ui/EntityInput.svelte, src/lib/ui/LoginForm.svelte, src/lib/ui/LogoutForm.svelte, src/lib/ui/ManageMembershipItem.svelte, src/lib/ui/PersonaInput.svelte, src/lib/ui/PropertyEditor.svelte, src/lib/ui/SpaceInput.svelte, src/lib/ui/view/Home.svelte
The `PendingButton` could be used in a few places that it wasn't. The main thing it does is show a pending animation without changing the button's size. It also doesn't need `type="button"` after this Felt PR: https://github.com/feltcoop/felt/pull/190
=> use pending button where appropriate

src/lib/app/events.test.ts, src/lib/server/services.test.ts, src/lib/util/testDbHelpers.ts, src/lib/vocab/community/CommunityRepo.test.ts, src/lib/vocab/community/communityServices.test.ts, src/lib/vocab/entity/EntityRepo.test.ts, src/lib/vocab/membership/membershipServices.test.ts, src/lib/vocab/persona/personaService.test.ts, src/lib/vocab/space/spaceServices.test.ts, src/lib/vocab/tie/TieRepo.test.ts
Simplifies tests to always receive an optional `RandomVocabContext` along with the `db` in the test context. It's an extremely lightlweight class now that it does no caching, so it just makes code more concise.
=> add RandomVocabContext to db test context

src/lib/server/servicesIntegration.test.ts
Improves the service integration tests to use service calls instead of repo methods for deletions. Deleting a membership through the service causes orphaned communities to be cleaned up, so I did a todo to add a second persona to the test so we could continue testing deleting a membership and a community. It doesn't test the orphan cleanup behavior because that has a standalone test in the membership services tests.
Also changes some bits of code to be more concise, mainly using `unwrap`.
=> improve service integration tests

src/lib/vocab/membership/membershipServices.test.ts, src/lib/vocab/membership/membershipServices.ts
Currently, trying to create a duplicate membership results in a Postgres error because of foreign key constraints. This changes it to explicitly check and return a useful error message and status code, also simplifying the test.
=> check for duplicate memberships

src/lib/server/servicesIntegration.test.ts, src/lib/ui/view/Home.svelte, src/lib/vocab/community/communityServices.test.ts, src/lib/vocab/entity/entityServices.test.ts, src/lib/vocab/random.ts
Changes the random vocab to use `createEntityService` and `createTieService` instead of the repos. Also extracts some logic from the service integration test to a new `entityServices.test.ts`, and simplifies the service integration tests to use `random` instead of duplicating the same logic -- random previously used repos, but now that it uses services there's no reason for the integration test to be more complicated.
=> use services in random

.github/workflows/check.yml, src/lib/app/eventTypes.ts, src/lib/db/migrations/00020-tie-entities-directory.js, src/lib/server/random.ts, src/lib/server/servicesIntegration.test.ts, src/lib/ui/EntityInput.svelte, src/lib/ui/view/Board.svelte, src/lib/ui/view/Forum.svelte, src/lib/ui/view/Notes.svelte, src/lib/ui/view/Room.svelte, src/lib/ui/view/Todo.svelte, src/lib/vocab/entity/entityEvents.ts, src/lib/vocab/entity/entityServices.ts, src/lib/vocab/random.ts, src/lib/vocab/tie/TieRepo.test.ts
This PR handles Part 2 of the directory architectural refactor.
It introduces a migration query that connects all orphan entities (i.e. all those without a tie where they are the dest, i.e. any top level or non connected entities) and ties them to their space's Directory (introduced in  #300 )
It also expands the CreateEntity service params to include a `source_id` attribute & option `type` (which defaults to HasItem) to make sure no Entity is created as an orphan from here out.
Lastly, it updates all uses of CreateEntity on the front end to now include the directory_id in the call (except in Todo, where we get to condense some existing Tie logic down to a single call! 🎉 )
=> Directory part 2

src/lib/app/eventTypes.ts, src/lib/vocab/entity/EntityRepo.ts, src/lib/vocab/entity/entityEvents.ts, src/lib/vocab/entity/entityServices.ts
This PR tries to touch as little of the interface as possible, while replacing the query for Entities with the new directory crawl query.
Some future work off of this:
Move Entity stores away from indexing off of space_id
Modify event to expect both entities & ties to return
=> Directory PHASE 3

src/lib/ui/Avatar.svelte, src/lib/ui/CommunityAvatar.svelte, src/lib/ui/MainNav.svelte, src/lib/ui/PersonaAvatar.svelte, src/lib/ui/RoomItem.svelte, src/lib/ui/TodoItem.svelte, src/lib/ui/WorkspaceHeader.svelte, src/lib/ui/contextmenu/contextmenu.ts
Changes some usage of the plain `Avatar` to `CommunityAvatar` and `PersonaAvatar`. The main reason besides concision is that the latter have contextmenu behavior automatically.
Also changes their API to make the contextmenu optional. In some cases the contextmenu is already added because of a parent entity. I'm not sure if these can be de-duplicated automatically -- it may require explicitly adding a group param. (type isn't enough; you may have an entity/persona/etc in the context of another entity, and want to display both)
Some usage of `Avatar` is more appropriate, like if a `community` or `persona` object isn't available, like the icon preview when creating a new community.
=> prefer specialized avatars when appropriate

src/lib/app/contextmenu/CommunityContextmenu.svelte, src/lib/app/contextmenu/EntityContextmenu.svelte, src/lib/app/eventTypes.ts, src/lib/app/events.ts, src/lib/app/mutations.ts, src/lib/server/random.ts, src/lib/server/services.ts, src/lib/ui/CommunityDelete.svelte, src/lib/ui/SpaceDelete.svelte, src/lib/vocab/entity/EntityRepo.ts, src/lib/vocab/entity/entityEvents.ts, src/lib/vocab/entity/entityMutations.ts, src/lib/vocab/entity/entityServices.ts
This PR adds some friction to the existing SpaceDelete modal, as well as adding one for CommunityDelete too.
Since Entities are a little more lightweight, I didn't add one there. I did rename the SoftDelete endpoint to match our Delete::Erase nomenclature though.
1 note: I'm not 100% sure on the input check logic in the modals. It doesn't seem to immediately parse the name, so I may have chosen the wrong event?
=> Add delete modal friction

src/lib/vocab/entity/entityServices.test.ts, src/lib/vocab/entity/entityServices.ts, src/lib/vocab/tie/tieHelpers.ts
Adds a helper for extracting unique ids from ties. Even if the code that uses it is temporary, I thought it was worthwhile, but I'm alright with closing this issue and not merging. This helper and pattern does a lot less work than the previous version.
=> add tie entity ids helper

package-lock.json, package.json
Upgrades Gro -- I [removed some behavior that's redundant with SvelteKit/Vite](https://github.com/feltcoop/gro/pull/321), and changed it to [always build before running tasks](https://github.com/feltcoop/gro/pull/322), which means you shouldn't have to run `gro dev` before any tasks, nor `gro clean`, unless there's bugs. It'll be slightly slower, usually less than a couple hundred milliseconds on my underpowered laptop.
=> upgrade gro

src/lib/app/contextmenu/SpaceContextmenu.svelte, src/lib/app/eventTypes.ts, src/lib/app/events.test.ts, src/lib/ui/uiEvents.ts, src/lib/ui/uiMutations.ts, src/lib/ui/view/EntityExplorer.svelte, src/lib/util/randomEventParams.ts
To make our events recordable+scriptable, their params need to be serializable. This is already true for all service events because we send params as JSON to the server, but 2 client events use stores, so this changes the first of them to have serializable params instead of a store.
=> change ViewSpace to be serializable

src/lib/ui/uiMutations.ts
Changes the client-side `Ping` handler to log the time it took to do the roundtrip in milliseconds.
=> log ping time

src/lib/ui/Marquee.svelte, src/lib/ui/MarqueeNav.svelte
Tiny tweak to the marquee header to change the text "Members" to the space icon, and only show the user count if it's >1. Might be some other minor changes to do while we're looking at it.
=> add space icon to marquee header

src/lib/app/contextmenu/LinkContextmenu.svelte, src/lib/ui/UnicodeIcon.svelte, src/lib/ui/contextmenu/contextmenu.ts
Tweaks the contextmenu styling for links to look like the other menu entries.
Also removes a hack for Firefox Mobile that appears unnecessary.
=> improve contextmenu link styling

src/lib/app/contextmenu/AppContextmenu.svelte
Changes `Log out` to be a regular menuitem on the contextmenu instead of a button.
I looked into keeping this a `PendingButton`, but the contextmenu currently doesn't handle async actions. As soon as an item is activated, it closes the contextmenu. It seems likely we'll want to support async actions -- I'm going to look at that next, so this PR may be obsolete if that works out. The downside of this PR is that you don't see a spinner, and failure is silent.
Using a button in the contextmenu also gets tricky with styling -- it may be that the `LogoutForm` isn't appropriate here, and we need a separate `LogoutButton`. It may be that *all* contextmenu items should be buttons. In that case, any styling hacks we do now wouldn't be used later, so I think it's best to just punt.
=> use a menuitem instead of button for logout on contextmenu

src/lib/ui/SpaceInput.svelte, src/lib/vocab/space/spaceMutations.ts
Currently we do a URL redirect in the `CreateSpace` mutation to go to the newly created space, but there's two problems with it:
- it errors and doesn't work (it's not worth checking but I'm fairly certain a recent SvelteKit upgrade broke it -- the problem is `page` from `'$app/stores'` uses `getContext` under the hood which can only be called during component initialization)
- it's not the right UX because `CreateSpace` events may be broadcasted -- you don't want someone else making a space to change your location!
I think it makes sense to generally put redirects in the components, so this moves it and I looked at others. There's at least 2 more instances of this that may be broken and/or the wrong UX. I'll look at those in a followup.
=> fix create space redirect

src/lib/ui/Marquee.svelte, src/lib/ui/SocketConnection.svelte, src/lib/ui/SocketConnectionControls.svelte, src/lib/ui/socket.ts, src/routes/__layout.svelte
Renames `SocketConnection` to `SocketConnectionControls` and adds `SocketConnection` to extract a bit of logic out of the main layout. It should change no behavior, the idea is to keep the layout tidy and make the websocket less tightly coupled to it.
=> extract websocket component

src/lib/ui/CommunityNav.svelte, src/lib/ui/Luggage.svelte, src/lib/ui/MarqueeButton.svelte
Makes the luggage and marquee buttons square. I tried making just the top corner have zero radius, but it looks a bit strange, and the community/space links all have square corners, so I think this is better.
I don't love how the outline style for the focused element gets cut off for various reasons, like going off the page (see the community links) or being overlapped by other elements (see the space links), but I'm not sure what to do about it.
=> remove border radius from luggage and marquee buttons

src/lib/app/eventTypes.gen.ts, src/lib/app/eventTypes.ts, src/lib/db/migrations/00025-directory-data-space-community-ids.js, src/lib/util/randomVocab.ts, src/lib/vocab/entity/entityData.ts, src/lib/vocab/space/spaceEvents.ts, src/lib/vocab/space/spaceServices.test.ts, src/lib/vocab/space/spaceServices.ts
We should be able to detect directories with type safety via `'space_id' in $entity.data`, they continue to have `type: 'Collection'` but no longer have `name: 'directory'`.
=> add `data.space_id` for directory entities

src/lib/ui/MarqueeNav.svelte, src/lib/ui/MemberItem.svelte
Persona icons in the community member list were a bit big, now they're smaller and spaced apart with padding.
=> shrink the member item persona icons

src/lib/ui/Luggage.svelte
Makes the luggage contents scale up slightly when the button is `:active` (clicking or pressing the spacebar). Doesn't add a transition animation or hover state (because the button already has its own), is very minimal, might be something we extract into a helper class.
=> add a subtle click animation to the luggage

src/lib/ui/Marquee.svelte
This "edit space" button that appeared in the marquee in devmode was bugged because we don't have typesafety on our dialog components (I think I can see a way to implement it, main thing is how to generate types from a Svelte component).
Rather than fixing the bug, I'm removing the button because this predated contextmenus.
=> fix edit space button in devmode

src/lib/ui/PropertyEditor.svelte, src/lib/ui/style.css
Changes the property editor buttons to always show "cancel" or "edit", and then displays "reset" and "save" below instead of replacing "cancel" when there are changes. Also makes the buttons fill the space and makes the textarea a bit taller for now.
=> improve property editor buttons

package-lock.json, package.json
I simplified the implementation of `@feltcoop/svelte-gettable-stores` quite a bit here: https://github.com/feltcoop/svelte-gettable-stores/pull/1
this upgrades the dep
=> upgrade `@feltcoop/svelte-gettable-stores`

package-lock.json, package.json, src/lib/ui/contextmenu/Contextmenu.svelte, src/routes/__layout.svelte
Changes the contextmenu opener key to be `ctrl+shift+Backtick` for now. Also makes `Backtick` toggle the main nav.
todo
Future: create a `Hotkeys` component or similar
=> change contextmenu hotkeys and add hotkey to toggle main menu

src/lib/app/contextmenu/EntityContextmenu.svelte, src/lib/app/eventTypes.ts, src/lib/server/servicesIntegration.test.ts, src/lib/ui/EntityEditor.svelte, src/lib/ui/view/Todo.svelte, src/lib/util/randomEventParams.ts, src/lib/vocab/entity/EntityRepo.ts, src/lib/vocab/entity/entityEvents.ts, src/lib/vocab/entity/entityMutations.ts, src/lib/vocab/entity/entityServices.test.ts, src/lib/vocab/entity/entityServices.ts, src/lib/vocab/membership/membershipServices.ts, src/lib/vocab/space/spaceEvents.ts, src/lib/vocab/space/spaceMutations.ts, src/lib/vocab/space/spaceServices.ts
This PR adds a query to find any orphaned entities & then makes a call to delete them when deleting other entities.
Additional work:
=> First pass on query & orphan cleanup

src/lib/vocab/entity/entityServices.ts
Feel free to reject, this is a no-op that rewrites a loop to be more readable IMO but it's subjective. My reasoning is that it doesn't need to track a state var, and doesn't need the `if` nesting. The `while (true) {` pattern doesn't always work but I usually prefer it when possible.
=> tweak a loop for subjective readability

src/lib/ui/ui.ts
This PR adds localStores around the luggage & marquee state stores in UI.
As an aside, I'm not sure if this is just a local dev thing, but there's some noticeable pop-in on the elements before collapse when saved as collapsed. Any thoughts?
=> Use localStore for managing luggage & marquee state
